name: store_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"


dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependencies:
  build_runner: ^2.3.3
  store_api:
    path: ../store_api
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
